package com.tomslabs.exercises.javaImpatnient.chapter5;

public class Exercise7 {
    // ex could be thrown in contructor, try with resources won't know about this and exception will have to be handled by invoking code
}
